### ISSUE TITLE
Treating IDs as strings

### ISSUE THREAD

**Issue by maximmass** [basespace/basespace-java-sdk#1]
BaseSpaceEntity has the Id field defined as a long. Although this works for now in most (but not all cases such as AppSession), it's better in the long run if we treat this as an opaque string. This may give us the flexibility later to adapt the IDs to non-predictable/enumerable values in the future.

Of course we would never change existing ID values for resources.

**Comment by jdlogicman** [comment]
I agree that existing IDs will not change once we release, but IDs must be strings. That is in the API spec.
